stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/preprocessed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/preprocessed
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/features
    - src/models/model_building.py
    params:
    - model_building.use_label_encoder
    - model_building.eval_metric
    outs:
    - models/model.joblib
  evaluation:
    cmd: python src/models/evaluation.py
    deps:
    - data/features
    - models/model.joblib
    - src/models/evaluation.py
    metrics:
    - results.json:
        cache: false
